apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: onecloud
  name: k8s-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backend
  template:
    metadata:
      labels:
        app: k8s-backend
    spec:
      containers:
        - name: k8s-backend
          image: k8srepo.azurecr.io/k8s/backend-api:latest
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
      imagePullSecrets:
        - name: acr-auth
