apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-frontend
  namespace: onecloud
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ocaks.azurecr.io/k8s/frontend:latest
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
      imagePullSecrets:
        - name: acr-auth

